name: Workflow-3

on:
    deployment

jobs:
    job-1:
        runs-on: ubuntu-latest

        steps:
        - name: Print Hello World
          run: echo "The branch running this is:" ${{ github.ref_name }}