name: Workflow 2

on:
    workflow_run:
        workflows: ["Workflow 1"]
        types: [completed]
        branches:
          - 'main'
          - 'develop'

jobs:
    job-0:
        name: Job 0
        runs-on: ubuntu-latest    
        environment: ENV-1 
        outputs:
          var_1: ${{ steps.init.outputs.var_1 }}
          var_2: ${{ steps.init.outputs.var_2 }}
        
        steps:        
          - name: Make environment variables global 
            id: init
            run: |
              echo "var_1=${{ vars.VAR_1 }}" >> $GITHUB_OUTPUT
              echo "var_2=${{ vars.VAR_2 }}" >> $GITHUB_OUTPUT
    job-1:
        name: Job 1
        needs: job-0
        if: ${{ needs.job-0.outputs.var_1 == 'true' &&  needs.job-0.outputs.var_2 == github.event.workflow_run.head_branch && github.event.workflow_run.conclusion == 'success' }}
        runs-on: ubuntu-latest
        steps:
            - name: Echo environment variable 1
              run: echo VAR_1 = ${{ needs.job-0.outputs.var_1 }}

            - name: Echo environment variable 2
              run: echo VAR_2 = ${{ needs.job-0.outputs.var_2 }}
            
            - name: Print Head Branch
              run: echo "The branch running this is:" ${{ github.event.workflow_run.head_branch }}

            - name: Print Parent Workflow Run Status
              run: echo "The parent workflow run status is:" ${{ github.event.workflow_run.conclusion }}
            
            - name: Print Commit Hash
              run: echo "The commit hash is:" ${{ github.sha }}