name: Workflow-2

on:
    workflow_run:
        workflows: ["Workflow-1"]
        types:
            - completed

jobs:
    job-0:
        runs-on: ubuntu-latest    
        environment: ENV-1 
        outputs:
          var_1: ${{ steps.init.outputs.var_1 }}
          var_2: ${{ steps.init.outputs.var_2 }}
        
        steps:        
          - name: Make environment variables global 
            id: init
            run: |
              echo "var_1=${{ vars.VAR_1 }}" >> $GITHUB_OUTPUT
              echo "var_2=${{ vars.VAR_2 }}" >> $GITHUB_OUTPUT
    job-1:
        needs: job-0
        if: ${{ needs.job-0.outputs.var_1 == 'true' }}
        runs-on: ubuntu-latest
        environment: ENV-1
        steps:
            - name: Echo environment variable
              run: echo VAR_1 = ${{ needs.job-0.outputs.var_1 }}

            - name: Echo environment variable
              run: echo VAR_2 = ${{ needs.job-0.outputs.var_2 }}