name: Workflow-1

on:
    workflow_dispatch:
    push:


jobs:
    job-1:
        runs-on: ubuntu-latest

        steps:
        - name: Print Workflow-1
          run: echo "Workflow-1 is running..."
            
        - name: Print Commit Hash
          run: echo "The commit hash is:" ${{ github.sha }}