name: Workflow-2

on:
    workflow_run:
        workflows: ["Workflow-1"]
        types:
            - completed

jobs:
    job-0:
        runs-on: ubuntu-latest    
        environment: ENV-1 
        outputs:
          stageEnv: ${{ steps.init.outputs.stageEnv }}
        
        steps:        
          - name: Make environment variables global 
            id: init
            run: |
              echo "stageEnv=${{ vars.TEST }}" >> $GITHUB_OUTPUT
    job-1:
        if: ${{ vars.TEST == 'true' }}
        runs-on: ubuntu-latest
        environment: ENV-1
        steps:
            - name: Echo environment variable
              run: echo ${{ vars.TEST }}

            # Add your desired steps here