name: Workflow-2

on:
    workflow_run:
        workflows: ["Workflow-1"]
        types:
            - completed

jobs:
    job-0:
        runs-on: ubuntu-latest    
        environment: ENV-1 
        outputs:
          stageEnv: ${{ steps.init.outputs.stageEnv }}
        
        steps:        
          - name: Make environment variables global 
            id: init
            run: |
              echo "stageEnv=${{ vars.TEST }}" >> $GITHUB_OUTPUT
    job-1:
        needs: job-0
        if: ${{ needs.job-0.outputs.stageEnv == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Echo environment variable
              run: echo ${{ needs.job-0.outputs.stageEnv }}

            # Add your desired steps here