name: Workflow-2

on:
    workflow_run:
        workflows: ["Workflow-1"]
        types:
            - completed

jobs:
    job-1:
        environment: 'ENV-1'
        if: ${{ vars.TEST == 'true' }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Echo environment variable
              run: echo ${{ vars.TEST }}

            # Add your desired steps here